#!/bin/bash

mkdir -p /opt/bin
mkdir -p /etc/kubernetes/manifests
mkdir -p /etc/systemd/system/flanneld.service.d

wget -q \
  -O /tmp/kubernetes.tar.gz \
  https://dl.k8s.io/v1.7.6/kubernetes-server-linux-amd64.tar.gz

tar xf /tmp/kubernetes.tar.gz -C /opt

cat << EOF > /etc/systemd/system/myip.service
[Unit]
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStartPre=/usr/bin/wget -q -O /opt/bin/myip https://dl.condi.me/myip
ExecStartPre=/usr/bin/chmod +x /opt/bin/myip
ExecStart=/opt/bin/myip -w /etc/myip

[Install]
WantedBy=default.target
EOF

cat << EOF > /etc/systemd/system/kubelet.service
[Unit]
After=myip.service
Wants=myip.service

[Service]
EnvironmentFile=/etc/myip
ExecStart=/opt/kubernetes/server/bin/kubelet \\
  --address=127.0.0.1 \\
  --pod-manifest-path=/etc/kubernetes/manifests \\
  --api-servers=http://localhost:8080 \\
  --node-ip=\${MYIP} \\
  --cluster-dns=\${MYIP} \\
  --cadvisor-port=0
Restart=always
RestartSec=10

[Install]
WantedBy=default.target
EOF

cat << EOF > /etc/systemd/system/kube-apiserver.service
[Service]
ExecStart=/opt/kubernetes/server/bin/kube-apiserver \\
   --bind-address=127.0.0.1 \\
   --service-cluster-ip-range=10.0.0.0/16 \\
   --etcd-servers=http://127.0.0.1:4001 \\
   --storage-backend etcd2 \\
   --logtostderr=true
Restart=always
RestartSec=10

[Install]
WantedBy=default.target
EOF

cat << EOF > /etc/systemd/system/kube-controller-manager.service
[Service]
ExecStart=/opt/kubernetes/server/bin/kube-controller-manager \\
  --master=http://localhost:8080 \\
  --address=127.0.0.1
Restart=always
RestartSec=10

[Install]
WantedBy=default.target
EOF

cat << EOF > /etc/systemd/system/kube-proxy.service
[Service]
ExecStart=/opt/kubernetes/server/bin/kube-proxy \\
  --master=http://localhost:8080 \\
  --healthz-bind-address=127.0.0.1 \\
  --cluster-cidr=10.0.0.0/16
Restart=always
RestartSec=10

[Install]
WantedBy=default.target
EOF

cat << EOF > /etc/systemd/system/kube-scheduler.service
[Service]
ExecStart=/opt/kubernetes/server/bin/kube-scheduler \\
  --master=http://localhost:8080 \\
  --address=127.0.0.1
Restart=always
RestartSec=10

[Install]
WantedBy=default.target
EOF

cat << EOF > /etc/systemd/system/flanneld.service.d/override.conf
[Service]
ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '{"Network": "10.0.0.0/16", "Backend": {"Type": "host-gw"}}'
EOF

cat << EOF > /etc/kubernetes/manifests/kubedns.yml
apiVersion: v1
kind: Pod
metadata:
  name: kubedns
spec:
  hostNetwork: true
  containers:
  - name: "kube-dns"
    image: gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.4
    args:
    - --kube-master-url=http://localhost:8080
    - --domain=cluster.local.
    - --dns-port=53
    - --healthz-port=0
EOF

systemctl daemon-reload
systemctl enable --now --wait myip
systemctl enable --now etcd2
systemctl enable --now flanneld
systemctl enable --now kubelet
systemctl enable --now kube-apiserver
systemctl enable --now kube-controller-manager
systemctl enable --now kube-proxy
systemctl enable --now kube-scheduler

